### ISSUE TITLE
How to use the tool ?

### ISSUE THREAD

**Issue by kyisoethin** [portcullislabs/tlsplayback#1]
My nginx server is local. My web browser is Firefox Nightly.
I have configured nginx web server with boring ssl that support tls 1.3.
I run the tool as follow.
```
root@kst-VirtualBox:~/tlsplayback# python3 tls_playback.py -h 127.0.0.1

 Setting up the proxy...
 Done. The proxy is ready.
```

I first access web server from browser. And ,after about five minutes, I access again. But the python program shows nothing about early data.

In what place am I wrong?

**Comment by kyisoethin** [comment]
Thanks @timb-machine for your reply.
I managed to do it by channging proxy setting.
But the web page does not show.
I change "print" instead of "print_dbg" in the script and it showed as follow.
```
root@kst-VirtualBox:~/tlsplayback/tlsplayback# python3 tls_playback.py -h localhost -l 127.0.0.1 --listen_port=4443 -p 443

 Setting up the proxy...
 Done. The proxy is ready.

Client Connection accepted
Server connection established
Entering into select() loop
Packets received from client: [{'type': 67, 'legacy_record_version': b'ON', 'length': 20037}]
Packets sent to the server
Packets received from server: [{'type': 72, 'legacy_record_version': b'TT', 'length': 20527}]
Packets sent to the client
Client Connection accepted
Server connection established
Entering into select() loop

```
But in the browser, it showed as follow.

```
Hmm. We’re having trouble finding that site.

We can’t connect to the server at localhost.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.
```
When I try in chrome, it show the error

> err_tunnel_connection_failed

Please help my problem again.

**Comment by kyisoethin** [comment]
Update

When I viewed the traffic with wireshark, it showed as following picture inside the link.

![screenshot from 2018-12-26 18-00-01](https://user-images.githubusercontent.com/11909371/50444713-6c38ef80-0938-11e9-9c66-40780b0997f2.png)

**Comment by alfon-git** [comment]
Hello @kyisoethin, 

The tool was designed to simulate a real MITM attack scenario, where the victim user does not know the replay attack is happening. You don't need to configure a proxy in your web browser. 

To test the attack, you have to redirect somehow the traffic from the web browser to the tool. In all my tests I used iptables to redirect the traffic. You should create an iptables rule to redirect the traffic to the port in which the tool is listening. The tool will then connect to the server specified with -h <host> -p <port>. 

I suggest you to run the web server and the tool in a different VM than your web browser in order to avoid problems with the iptables redirection.
